image: docker:latest
services:
  - docker:dind

test:
 stage: test
 script:
   - cd thermo_genomika
   - docker build -t "thermo:base" .
   - cd ..
   - docker run -v $PWD:/var/www/ thermo:base /bin/bash -c "cd /var/www && ls" 