# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thermouser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='thermouser',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome completo'),
        ),
        migrations.AddField(
            model_name='thermouser',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome abreviado'),
        ),
    ]
