# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20160809_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thermouser',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='thermouser',
            name='last_access',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Acess'),
        ),
        migrations.AlterField(
            model_name='thermouser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='thermouser',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='thermouser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active ?'),
        ),
        migrations.AlterField(
            model_name='thermouser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Is staff ?'),
        ),
        migrations.AlterField(
            model_name='thermouser',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Short Name'),
        ),
        migrations.AlterField(
            model_name='thermouser',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='User'),
        ),
    ]
