# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-13 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catcher', '0002_auto_20180313_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicestatus',
            name='allowed_address',
        ),
        migrations.DeleteModel(
            name='DeviceStatus',
        ),
    ]
