# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-13 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catcher', '0003_auto_20180313_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_sent', models.BooleanField(default=False, verbose_name='E-mail Sent?')),
                ('last_connection', models.BooleanField(default=False, verbose_name='Last Connection')),
                ('check_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Check Date')),
                ('allowed_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device_status', to='catcher.AllowedAddress')),
            ],
            options={
                'verbose_name': 'Device Status',
                'verbose_name_plural': 'Devices Status',
            },
        ),
    ]
