# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-14 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catcher', '0004_devicestatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicestatus',
            name='email_sent',
        ),
        migrations.AddField(
            model_name='devicestatus',
            name='check_offline',
            field=models.BooleanField(default=False, verbose_name='Check Offline'),
        ),
    ]
