# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-21 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catcher', '0005_auto_20180314_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicestatus',
            name='previous_last_connection',
            field=models.BooleanField(default=False, verbose_name='Previous Last Connection'),
        ),
    ]
