# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catcher', '0006_thermoinfo_allowed_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='thermolog',
            name='ocurred_error',
            field=models.BooleanField(default=False, verbose_name='Ocurred error ?'),
        ),
    ]
