# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-29 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catcher', '0008_auto_20160803_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedaddress',
            name='device_name',
            field=models.CharField(default='', max_length=20, verbose_name='Device Name'),
        ),
    ]
