# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-23 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catcher', '0009_allowedaddress_device_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedaddress',
            name='min_temperature',
            field=models.FloatField(default=18.0, verbose_name='Minimum temperature allowed'),
        ),
        migrations.AlterField(
            model_name='allowedaddress',
            name='max_temperature',
            field=models.FloatField(default=20.0, verbose_name='Maximum temperature allowed'),
        ),
    ]
