# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-14 19:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catcher', '0008_auto_20160803_1143'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceChecklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_temp', models.FloatField(verbose_name='Temperature average')),
                ('max_temp', models.FloatField(verbose_name='Max. temperature')),
                ('min_temp', models.FloatField(verbose_name='Min. temperature')),
                ('date_max_temp', models.DateTimeField(verbose_name='Max. temperature date')),
                ('date_min_temp', models.DateTimeField(verbose_name='Min. temperature date')),
                ('is_checked', models.BooleanField(verbose_name='Is checked ?')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='catcher.AllowedAddress', verbose_name='Device')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_responsible', to=settings.AUTH_USER_MODEL, verbose_name='Responsible')),
            ],
            options={
                'verbose_name': 'Device Checklist',
                'verbose_name_plural': 'Devices Checklists',
            },
        ),
    ]
