# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-13 19:11
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catcher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceChecklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2018, 3, 13, 19, 11, 40, 589447, tzinfo=utc), verbose_name='Date')),
                ('avg_temp', models.FloatField(verbose_name='Temperature average')),
                ('max_temp', models.FloatField(verbose_name='Max. temperature')),
                ('min_temp', models.FloatField(verbose_name='Min. temperature')),
                ('date_max_temp', models.DateTimeField(verbose_name='Max. temperature date')),
                ('date_min_temp', models.DateTimeField(verbose_name='Min. temperature date')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Is checked ?')),
                ('admeasurements', models.IntegerField(default=0, verbose_name='Admeasurements')),
                ('temp_not_allwd', models.IntegerField(default=0, verbose_name='Temperatures not allowed')),
                ('check_date', models.DateField(blank=True, null=True, verbose_name='Check date')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='catcher.AllowedAddress', verbose_name='Device')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_responsible', to=settings.AUTH_USER_MODEL, verbose_name='Responsible')),
            ],
            options={
                'verbose_name': 'Device Checklist',
                'verbose_name_plural': 'Devices Checklists',
            },
        ),
        migrations.AlterUniqueTogether(
            name='devicechecklist',
            unique_together=set([('date', 'device')]),
        ),
    ]
