# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 00:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_auto_20160814_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicechecklist',
            name='admeasurements',
            field=models.IntegerField(default=0, verbose_name='Admeasurements'),
        ),
        migrations.AddField(
            model_name='devicechecklist',
            name='temp_not_allwd',
            field=models.IntegerField(default=0, verbose_name='Temperatures not allowed'),
        ),
        migrations.AlterField(
            model_name='devicechecklist',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 8, 15, 0, 56, 5, 228519, tzinfo=utc), verbose_name='Data'),
        ),
    ]
