# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-18 12:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0004_auto_20160818_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicechecklist',
            name='check_date',
            field=models.DateField(blank=True, null=True, verbose_name='Check date'),
        ),
        migrations.AlterField(
            model_name='devicechecklist',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 8, 18, 12, 48, 34, 104001, tzinfo=utc), verbose_name='Date'),
        ),
    ]
