# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 11:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0006_auto_20160819_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicechecklist',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 8, 19, 11, 26, 47, 778801, tzinfo=utc), unique=True, verbose_name='Date'),
        ),
    ]
