# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-29 17:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0008_auto_20160822_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicechecklist',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 8, 29, 17, 56, 15, 446384, tzinfo=utc), verbose_name='Date'),
        ),
    ]
