# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-14 10:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0008_auto_20180313_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicechecklist',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 3, 14, 10, 30, 17, 97174, tzinfo=utc), verbose_name='Date'),
        ),
    ]
