# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-13 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(default='', max_length=150, verbose_name='Local')),
                ('temperature', models.FloatField(blank=True, default=20, null=True, verbose_name='Temperature')),
                ('situation', models.CharField(max_length=50, verbose_name='Situation')),
                ('recipient_list', models.TextField(blank=True, verbose_name='Recipient list')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Mails Log',
                'verbose_name_plural': 'Mail Logs',
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active ?')),
            ],
            options={
                'verbose_name': 'Recipient',
                'verbose_name_plural': 'Recipients',
            },
        ),
    ]
