# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-13 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maillog',
            name='situation',
            field=models.CharField(max_length=20, verbose_name='Situation'),
        ),
    ]
