# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-13 21:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catcher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_sent', models.BooleanField(default=False, verbose_name='E-mail Sent ?')),
                ('last_connection', models.BooleanField(default=False, verbose_name='Last Connection')),
                ('check_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Check Date')),
                ('allowed_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catcher.AllowedAddress')),
            ],
            options={
                'verbose_name': 'Device Status',
                'verbose_name_plural': 'Devices Status',
            },
        ),
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Brand')),
                ('designed_by', models.CharField(max_length=50, verbose_name='Designed by')),
                ('version', models.CharField(max_length=10, verbose_name='Version')),
                ('date', models.DateField(default=datetime.datetime(2018, 3, 13, 21, 27, 53, 456758, tzinfo=utc), verbose_name='Date')),
            ],
            options={
                'verbose_name': 'System Information',
                'verbose_name_plural': 'Systems Informations',
            },
        ),
    ]
