# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 14:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160803_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systeminfo',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 8, 3, 14, 43, 0, 395403, tzinfo=utc), verbose_name='Date'),
        ),
    ]
