# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 12:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20160809_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systeminfo',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 8, 9, 12, 33, 16, 74741, tzinfo=utc), verbose_name='Date'),
        ),
    ]
