# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 13:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20160809_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systeminfo',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 8, 9, 13, 49, 10, 387322, tzinfo=utc), verbose_name='Date'),
        ),
    ]
