# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-14 19:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20160811_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systeminfo',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 8, 14, 19, 32, 37, 680651, tzinfo=utc), verbose_name='Date'),
        ),
    ]
