# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-14 23:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20160814_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systeminfo',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 8, 14, 23, 41, 42, 425108, tzinfo=utc), verbose_name='Date'),
        ),
    ]
