# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 00:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20160814_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systeminfo',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 8, 15, 0, 56, 5, 227514, tzinfo=utc), verbose_name='Date'),
        ),
    ]
