# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-18 12:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20160814_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systeminfo',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 8, 18, 12, 45, 46, 230916, tzinfo=utc), verbose_name='Date'),
        ),
    ]
