# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 11:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20160818_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systeminfo',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 8, 19, 11, 25, 57, 576877, tzinfo=utc), verbose_name='Date'),
        ),
    ]
