# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-22 13:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20160819_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systeminfo',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 8, 22, 13, 54, 51, 222826, tzinfo=utc), verbose_name='Date'),
        ),
    ]
